### ISSUE TITLE
Wrong path constructor in rule getter

### ISSUE THREAD

**Issue by webit-dev** [editorconfig-checker/editorconfig-checker.php#45]
Hey, just tested the master :)

The path constructor in the method to find a valid editorconfig is wrong: https://github.com/editorconfig-checker/editorconfig-checker.php/blob/master/src/EditorconfigChecker/Editorconfig/Editorconfig.php#L73

Lets say I run `bin/editorconfig-checker test-folder/*`, then the filelist returns a file like `test-folder/test/testfile.php`. The rootdir returns something like `/home/johndoe/git/editorconfig`. 

The line above then builds a wrong filepath `/home/johndoe/git/editorconfigest-folder/test/testfile.php` instead of `/home/johndoe/git/editorconfig/test-folder/test/testfile.php`.

Therefore no editorconfig is found, no rules are build (ruleset is empty) and all files are returned as valid (“Successfully checked 30968 lines in 168 files :)”).

**Comment by mstruebing** [comment]
Thanks for you quick feedback!

QuickFix: run `bin/editorconfig-checker ./test-folder/*` instead

Somehow I only tested with leading `./` - will provide a fix asap :)

**Comment by mstruebing** [comment]
Fixed see: https://github.com/editorconfig-checker/editorconfig-checker.php/commit/a928b1fdb4d2ecc09b5ff5caed02eb58d81a3b83

**Comment by mstruebing** [comment]
k

**Comment by pixelbrackets** [comment]
The fix does work, thanks :)

The autofix tools do now work as well :+1:

**Comment by pixelbrackets** [comment]
I have a general remark about this, since this filepath issue popped up several times. The script currently expects a relative filepath / file glob. The script then searches for all matching files and stores a list of relativ filenames.

The rule getter then builds an absolute path using the the starting point of the current CLI script and the filename. This path is used to get the .editorconfig. But as since this is generated it may not be real (eg. funny symlinks). Or it will return wrong results if the given file glob is absolute instead of relative.

I've had this issue and tried to build a working fallback. But had no satisfying result after several hours. So I'll write down my ideas, maybe you have a better/faster solution.

A) Catch the type if the fileglob and _always_ generate the list of files with absolute links only.

Old:
Run `bin/editorconfig-checker test-folder/*` to get filelist `test-folder/test/testfile.php`. Calculate root path `/home/johndoe/git/editorconfig`. Build new filepath `/home/johndoe/git/editorconfig/test-folder/test/testfile.php` in rule getter and search for the editorconfig file.

New: Run `bin/editorconfig-checker test-folder/*` to get filelist `/home/johndoe/git/editorconfig/test-folder/test/testfile.php`. The rule getter now uses the existing filepath only and does nit need to guess a path.
Bonus: The `-l` param will return the full filepath, which is easier to debug (the rule getter method is silent for users).

I tried to get an absolute path out of relative and or absolute file globs. Gave up eventually ;)

But I was able to run the [Simfony File Finder](https://symfony.com/doc/current/components/finder.html) which is able to do this relative and absolute file path juggling:

`src/EditorconfigChecker/Cli/Cli.php` → `getFileNames()`

            $finder = new \Symfony\Component\Finder\Finder();
            $finder->files()->in($fileGlob);
            foreach ($finder as $file) {
                print_r(['symfonyFileGlob' => $file->getRealPath()]);
            }

Using this component would require a rewrite of the exclude mechanism however. 

B) Require absolute file globs only.

This is behaviour is used by several CLI tools. I guess exactly because they want to avoid these issues ti relative paths. 

See editorconfig CLI:

https://github.com/editorconfig/editorconfig/wiki/FAQ#the-executable-of-editorconfig-core-does-not-accept-relative-paths-how-can-i-fix-that

> Since EditorConfig core executables are usually not supposed to be called by humans from command line, we did not support relative paths for simplicity across all implementations of EditorConfig cores. 

Also add a note about using absolute file globs only to the `Readme` and CLI Help Screen (and since this would break existing installations, add it to the release notes of a new mayor version).

Note that it is still possible to run relative file globs with a trick. Use the `$PATH`. Run `bin/editorconfig-checker $(pwd)/test-folder/*`, the variable will be expanded to the absolute path automatically.

C) Catch if the file glob is using an absolute filepath - break, return an exception. Also add a note about using relative file globs only to the `Readme` and CLI Help Screen.
